name: strainge
channels:
    - bioconda
    - conda-forge
    - anaconda
dependencies:
    - "python>=3.7"
    - pybind11
    - "scikit-bio>=0.5"
    - "scikit-learn>=0.24"
    - numpy
    - scipy
    - h5py
    - matplotlib
    - pysam
    - samtools
    - mummer4
    - bwa
    - pip
    - pip:
        - intervaltree
        - strainge
